name: BuildPlugin
on: [push]

jobs:
  build:
    uses: FriendsOfShopware/actions/.github/workflows/github.yml@main
    with:
      extensionName: 'AggroContactFormSenderMailPlugin'
      shopwareVersion: '6.5.2'
    secrets:
      ghToken: ${{ secrets.GH_TOKEN }}